#!/bin/sh

# Dependencies:
# convert wal xdotool xwallpaper

wall_dir=/home/subhankar/Pictures/wallpaper/

wall="$(find "$wall_dir" -type f -name "*.jpg" -o -name "*.png" | shuf -n1)"

#if [ -z "$1" ]; then
#  wall="$(find "$wall_dir" -type f -name "*.jpg" -o -name "*.png" | shuf -n1)"
#else
#  wall="$1"
#fi

#gsettings get org.gnome.desktop.background picture-uri "file://'$wall'"

#convert "$wall" ~/.local/share/bg.jpg
#xwallpaper --zoom ~/.local/share/bg.jpg
xwallpaper --zoom $wall

wal -c
wal -i $wall
#wal -i ~/.local/share/bg.jpg
xdotool key super+ctrl+r
